version: 0.0
os: linux
files:
  - source: .nuxt/
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
